ICON_DIR="$HOME/.local/share/applications/icons"

omarchy-webapp-install "HEY" https://app.hey.com "$ICON_DIR/HEY.png"
omarchy-webapp-install "Basecamp" https://launchpad.37signals.com "$ICON_DIR/Basecamp.png"
omarchy-webapp-install "WhatsApp" https://web.whatsapp.com/ "$ICON_DIR/WhatsApp.png"
omarchy-webapp-install "Google Photos" https://photos.google.com/ "$ICON_DIR/Google Photos.png"
omarchy-webapp-install "Google Contacts" https://contacts.google.com/ "$ICON_DIR/Google Contacts.png"
omarchy-webapp-install "Google Messages" https://messages.google.com/web/conversations "$ICON_DIR/Google Messages.png"
omarchy-webapp-install "ChatGPT" https://chatgpt.com/ "$ICON_DIR/ChatGPT.png"
omarchy-webapp-install "YouTube" https://youtube.com/ "$ICON_DIR/YouTube.png"
omarchy-webapp-install "GitHub" https://github.com/ "$ICON_DIR/GitHub.png"
omarchy-webapp-install "X" https://x.com/ "$ICON_DIR/X.png"
omarchy-webapp-install "Figma" https://figma.com/ "$ICON_DIR/Figma.png"
omarchy-webapp-install "Discord" https://discord.com/channels/@me "$ICON_DIR/Discord.png"
omarchy-webapp-install "Zoom" https://app.zoom.us/wc/home "$ICON_DIR/Zoom.png"
